name: CI CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: get
        uses: actions/checkout@v4

      - name: configure
        run: cmake -S . -B build -DBUILD_TESTS=ON
        working-directory: banking

      - name: build
        run: cmake --build build --config Debug
        working-directory: banking

      - name: run tests
        run: ./build/tests
        working-directory: banking

      - name: generate coverage
        working-directory: banking
        run: |
          pip install gcovr
          
          gcovr \
            --filter 'Account\.cpp$' \
            --filter 'Transaction\.cpp$' \
            --gcov-ignore-parse-errors \
            --exclude-unreachable-branches \
            --exclude-throw-branches \
            --exclude-lines-by-pattern '.*assert.*' \
            --lcov \
            -o coverage.info \
            .
          
      - name: upload to coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: banking/coverage.info
